### DISCUSSION TITLE
Auto Scan folder

### DISCUSSION THREAD

**Discussion by stilwellj1983** [Stirling-Tools/Stirling-PDF#1213] [Q&A] [answered]
I enjoy the software and it works great. 
I am trying to setup a scan folder that will scan in and OCR out I saw the discussion 989 titled setup auto scan folder and ocr new PDF.
I copied and updated the docker compose file and the json file. I have the json file in my scan_in folder and below are the contents of the two files. I am not sure what I am doing wrong but I left a file in the scan_in folder over night and it never moved to the scan_ocr folder. any help would be great. Thank you

docker-compose.yml
```
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
      - ./data/import-pdf:/pipeline/watchedFolders/scans_in
      - ./data/Completed-pdf:/pipeline/finishedFolders/scans_ocr
#      - /location/of/customFiles:/customFiles/
#      - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
```

ocr.json
```
{
  "name": "OCR",
  "pipeline": [
    {
      "operation": "/api/v1/misc/ocr-pdf",
      "parameters": {
        "languages": "eng",
        "sidecar": false,
        "deskew": false,
        "clean": false,
        "cleanFinal": false,
        "ocrType": "skip-text",
        "ocrRenderType": "hocr",
        "removeImagesAfter": false,
        "fileInput": "automated"
      }
    }
  ],
  "_examples": {
    "outputDir": "{outputFolder}/{folderName}",
    "outputFileName": "{filename}-{pipelineName}-{date}-{time}"
  },
  "outputDir": "{outputFolder}",
  "outputFileName": "{filename}"
}
```
