### DISCUSSION TITLE
Change footer HTML

### DISCUSSION THREAD

**Discussion by Osdop** [Stirling-Tools/Stirling-PDF#1219] [Q&A] [answered]
Hi all, I'm wondering how exactly I can overwrite html templates.

I just need to change the file footer.html 

Settings:
```
 security:
  enableLogin: false # set to 'true' to enable login
  csrfDisabled: true
  loginAttemptCount: 5 # lock user account after 5 tries
  loginResetTimeMinutes : 120 # lock account for 2 hours after x attempts

 system:
  defaultLocale: 'es-ES' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # Set to enable functionality which might need more testing before it fully goes live (This feature might 
   make no changes)
  showUpdate: false # see when a new update is available
  showUpdateOnlyAdmin: false # Only admins can see when a new update is available, depending on showUpdate it must be set to 'true'
  customHTMLFiles: true # Enable to have files placed in /customFiles/templates override the existing template html files

 ui:
  appName: Editor de PDF # Application's visible name
  homeDescription: PDF # Short description or tagline shown on homepage.
  appNameNavbar: PDF # Name displayed on the navigation bar

 endpoints:
  toRemove: ['add-password'] # List endpoints to disable (e.g. ['img-to-pdf', 'remove- 
  pages'])
  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

 metrics:
  enabled: true # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable

```
Docker-compose:
 ```
version: '3.3'
 services:
   stirling-pdf:
     image: frooodle/s-pdf:latest
     ports:
       - '8080:8080'
     volumes:
       - /etc/stirling:/usr/share/tessdata #Required for extra OCR languages
       - /etc/stirling:/configs
       - /etc/stirling/customFiles/static:/customFiles/static
 #      - /location/of/logs:/logs/
     environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=es_ES

```
I added the file in /etc/custom-files/templates/fragment/footer.html but no changes (after restart container)  

and
/etc/custom-files/templates/footer.html
/etc/custom-files/static/footer.html 
/etc/custom-files/static/templates/footer.html 
/etc/custom-files/static/templates/fragment/footer.html
