### DISCUSSION TITLE
How to  change localhost to 0.0.0.0

### DISCUSSION THREAD

**Discussion by eerison** [Stirling-Tools/Stirling-PDF#1942] [Q&A]
Hello guys I am trying to configure traefik, But as I can see it just accept connection via localhost

> 19:20:04.042 [main] INFO  s.software.SPDF.SPdfApplication - Navigate to http://localhost:8080

is it possible to change to `0.0.0.0:8080`?

**Comment by Frooodle** [comment]
That message is just generic message it's unrelated to actual network setup 
Have you tried other ips?

**Comment by eerison** [comment]
well it just works when I add ports on my docker-compose.yaml

```yaml
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    ports:
      - 8888:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdf.rule=Host(`pdf.my-host.com`)"
      - "traefik.http.routers.pdf.entrypoints=websecure"
      - "traefik.http.services.pdf.loadbalancer.server.port=8080"
      - "traefik.http.routers.pdf.tls.certresolver=cloudflare"
    networks:
      - proxy
    volumes:
      - $HOME_HOST/apps/stirling-pdf/trainingData:/usr/share/tessdata
      - $HOME_HOST/apps/stirling-pdf/extraConfigs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=pt_BR

networks:
  proxy:
    external: true
```

when I access via host: 192.168.x.x:8888 -> it works
when I access via internal docker network (via traefik) : pdf.my-host.com -> it does not work :(
