### DISCUSSION TITLE
How to disable the "prompt users to enable/disable analytics"

### DISCUSSION THREAD

**Discussion by Jackie264** [Stirling-Tools/Stirling-PDF#2060] [Q&A] [answered]
I've enabled analytics, but the prompt always displays.
<img width="1364" alt="Screenshot 2024-10-22 at 09 23 19" src="https://github.com/user-attachments/assets/887c2e22-34f5-407d-ba3f-3982c48ba138">

**Comment by Frooodle** [comment]
Can you show what your settings.yml looks like for system.enable analytics?

Thanks! Will try get this fixed now

**Reply by Jackie264** [reply]
```
system:
  defaultLocale: zh_CN # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: true # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # Set to enable functionality which might need more testing before it fully goes live (This feature might make no changes)
  showUpdate: true # see when a new update is available
  showUpdateOnlyAdmin: true # Only admins can see when a new update is available, depending on showUpdate it must be set to 'true'
  customHTMLFiles: false # enable to have files placed in /customFiles/templates override the existing template html files
  tessdataDir: /usr/share/tessdata # Path to the directory containing the Tessdata files. This setting is relevant for Windows systems. For Windows users, this path should be adjusted to point to the appropriate directory where the Tessdata files are stored.
  enableAnalytics: 'true' # Set to 'true' to enable analytics, set to 'false' to disable analytics, for enterprise users this is set to true
```

<img width="846" alt="Screenshot 2024-10-22 at 17 27 14" src="https://github.com/user-attachments/assets/5b07ccc9-7a5c-4423-9515-970d3df85eb4">
