### DISCUSSION TITLE
Is it possible to customize the content displayed on a webpage

### DISCUSSION THREAD

**Discussion by mattyx0011** [Stirling-Tools/Stirling-PDF#2098] [Q&A]
I have currently set everything up using Docker, but the webpage includes a 'nav-link go-pro-link' that links to 'stirlingpdf.com/pricing,' as well as a 'Powered by Stirling PDF' link that connects to an external URL. Could you please let me know if it’s possible to customize or remove these links? I would like to prevent users from  clicking and uploading files to external URLs. 
I will be grateful for any help you can provide..

` <li><a class="footer-link px-2" id="survey" target="_blank" href="https://stirlingpdf.info/s/cm28y3niq000o56dv7liv8wsu">Survey</a></li>`

` <a href="https://stirlingpdf.com" class="stirling-link">Stirling PDF</a>`

` <a href="https://stirlingpdf.com/pricing" class="nav-link go-pro-link" target="_blank" rel="noopener noreferrer" <span class="go-pro-badge">Upgrade to Pro</span>>`

**Comment by gravelfreeman** [comment]


**Reply by nktnet1** [reply]
As a workaround, you could use the "Element Picker" tool from uBlock Origin to persistently remove them.

Alternative is of course to fork the repo and make the change - see my answer [below](https://github.com/Stirling-Tools/Stirling-PDF/discussions/2098#discussioncomment-11757499).

**Comment by nktnet1** [comment]
NOTE:
- ideally, please use the official image and support the original project
- the official image will receive much more regular updates and is better maintained
- the fork below is only for a niche use-case with specific requirements

---

I am maintaining a fork with the following changes:
- removed modals/prompts for analytics/surveys
- remove external links that are not documentation
- removed enterprise button ("upgrade to pro")

Links:
- Changes (GitHub Pull Request): https://github.com/nktnet1/Stirling-PDF/pull/1/files
- Docker Images  (Docker Hub): https://hub.docker.com/repository/docker/nktnet/s-pdf/general

Example `docker-compose.yaml`:

```yaml
services:
  stirling-pdf:
    image: docker.io/nktnet/s-pdf:latest-fat
    ports:
      - 50000:8080
    volumes:
      - stirling_pdf_trainingdata:/usr/share/tessdata
      - stirling_pdf_extraconfigs:/configs
      - stirling_pdf_customfiles:/customFiles/
      - stirling_pdf_logs:/logs/
      - stirling_pdf_pipeline:/pipeline/
    environment:
      DOCKER_ENABLE_SECURITY: true
      SECURITY_ENABLE_LOGIN: true
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
      LANGS: en_US

volumes:
  stirling_pdf_trainingdata:
  stirling_pdf_extraconfigs:
  stirling_pdf_customfiles:
  stirling_pdf_logs:
  stirling_pdf_pipeline:
```

For anyone with similar requirements, rather than using my images though, I suggest maintaining your own fork/images.
