### DISCUSSION TITLE
Any idea to reduce RAM consumption?

### DISCUSSION THREAD

**Discussion by ivancarlosti** [Stirling-Tools/Stirling-PDF#2945] [Ideas]
This is my docker compose file, I limited it to consume 512MB RAM but it tops all these 512MB since startup.

```
name: pdf

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: pdf
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - '8020:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
      - ./customFiles:/customFiles
      - ./logs:/logs
    environment:
      DOCKER_ENABLE_SECURITY: "true"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      SYSTEM_DEFAULTLOCALE: en-US
      LANGS: en-US
      SYSTEM_MAXFILESIZE: "25"
      SYSTEM_GOOGLEVISIBILITY: "true"
    restart: unless-stopped
```

There is any way to let it run without eating too much RAM, at least when not doing any operation?

Thanks a lot and regards
