### DISCUSSION TITLE
Does custom_settings.yml support setting weasyprint & unoconvert paths?

### DISCUSSION THREAD

**Discussion by ssweber** [Stirling-Tools/Stirling-PDF#3058] [General]
Hello,

We have the following structure in configs/custom_settings.yml:

```yml
system:
  customPaths:
    operations:
      weasyprint: /usr/bin/weasyprint
      unoconvert: /usr/bin/unoconv
```

But it doesn't seem like Stirling is picking up that information:

```cmd
[main] WARN s.s.SPDF.config.ExternalAppDepConfig - Missing dependency: /opt/venv/bin/weasyprint - Disabling group: Weasyprint (Affected features: Markdown To PDF, Url To PDF, Html To PDF)
[main] WARN s.s.SPDF.config.ExternalAppDepConfig - Missing dependency: /opt/venv/bin/unoconvert - Disabling group: Unoconv (Affected features: File To PDF)
```

Is that supported?

Trying to resolve https://forum.cloudron.io/topic/13343/bad-paths-for-weasyprint-unoconv/6

**Comment by gramakri** [comment]
I added below to configs/custom_settings.yml and the settings are picked up. For some reason the weasyprint and unoconvert values are not.

```
ui:
  appName: 'App' # application's visible name
  homeDescription: 'Home Description' # short description or tagline shown on the homepage
  appNameNavbar: 'Navbar' # name displayed on the navigation bar
```
