### DISCUSSION TITLE
Null UI_APP_NAVBAR_NAME

### DISCUSSION THREAD

**Discussion by kintaro1981** [Stirling-Tools/Stirling-PDF#3133] [Q&A] [answered]
Hello,
this is part of my docker.compose.yaml:

```
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - /dati/dockerdata/stirlingpdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /dati/dockerdata/stirlingpdf/extraConfigs:/configs
      - /dati/dockerdata/stirlingpdf/customFiles:/customFiles/
      - /dati/dockerdata/stirlingpdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=it_IT
      - APP_LOCALE=it_IT
      - SYSTEM_DEFAULTLOCALE=it-IT
      - UI_APPNAME=Stirling-PDF
      - UI_HOMEDESCRIPTION=Strumento per la manipolazione e conversione PDF
      - UI_APP_NAVBAR_NAME=Home
      - SYSTEM_SHOW_UPDATE=true
      - SYSTEM_SHOW_UPDATE_ONLY_ADMIN=true
      - SYSTEM_ENABLEANALYTICS=false
```
From it I'm getting Null instead of the UI_APP_NAVBAR_NAME.

![immagine](https://github.com/user-attachments/assets/46e3e490-decb-4329-a8c3-324ac54f0825)
