### DISCUSSION TITLE
Customising using settings.yml

### DISCUSSION THREAD

**Discussion by samgaw58** [Stirling-Tools/Stirling-PDF#393] [General]
I have followed the simple instructions on customising the setup, both on the install version and the latest docker image. It made not one jot of difference. Is there another file I need to edit that I'm missing?

**Comment by Frooodle** [comment]
Can you show what your settings file contains?
Or how you are running docker imag etc?

**Comment by samgaw58** [comment]
Here is a copy of the settings.yml file. I have the same settings in both the installed version & the docker image (version 0.14.3)

# Welcome to settings file
# Remove comment marker # if on start of line to enable the configuration
# If you want to override with environment parameter follow parameter naming SECURITY_INITIALLOGIN_USERNAME

security:
  enableLogin: false # set to 'true' to enable login
  csrfDisabled: true

system:
  defaultLocale: 'en-GB' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow

  appName: My PDF # Application's visible name
  appNameNavbar: My PDF # Name displayed on the navigation bar

endpoints:
  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: true # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable
AutomaticallyGenerated:

**Comment by samgaw58** [comment]
The docker version is running on a Ubuntu 22.04 LXC container & the installed version is running on a 22.04 VM.

**Comment by Frooodle** [comment]
Ahh i think its a error in my config generation
the UI section should look like
```
ui:
  appName: exampleAppName # Application's visible name
  homeDescription: I am a description # Short description or tagline shown on homepage.
  appNameNavbar: navbarName # Name displayed on the navigation bar
  ```
  
  
I dont see that ui: in your above
