### DISCUSSION TITLE
Overwriting HTML Files

### DISCUSSION THREAD

**Discussion by snmabaur** [Stirling-Tools/Stirling-PDF#434] [Q&A]
Hi

I'm wondering how exactly I can overwrite html templates

Setup:
docker-compose.yml: 
```
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: always
    ports:
      - '32786:8080'
    volumes:
      - ./src/training-data:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ./src/extra-configs:/configs
      - ./src/custom-files:/customFiles
    environment:
      - DOCKER_ENABLE_SECURITY=false
```
settings.yml
```
security:
  enableLogin: false # set to 'true' to enable login
  csrfDisabled: true

system:
  defaultLocale: 'de-DE' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow

ui:
 appName: 'PDF Tool' # Application's visible name
 homeDescription: ' '
 appNameNavbar: 'Tool' # Name displayed on the navigation bar

endpoints:
  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: false # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable
```

I added the file `/src/custom-files/templates/fragment/navbar.html` but my changes are not visible

Updating CSS works, my updated file `/src/custom-files/static/css/generals.css` overrides the original one

I also tried following paths but they also do not work
```
/src/custom-files/static/templates/fragment/navbar.html
/src/custom-files/static/templates/navbar.html
/src/custom-files/static/navbar.html
```

Anyone has an idea how to manage that?

Thanks a lot :)
