### ISSUE TITLE
Why is customFiles/templates empty? No files? I need to overwrite them and customize html

### ISSUE THREAD

**Issue by pipuwong** [Stirling-Tools/Stirling-PDF#1131]
About "Custom HTML (Overwrite by File)", two files (static and templates) in customFiles are empty, how do I overwrite them? I have set customHTMLFiles: true

Please tell me how to customize html and how to overwrite the original file? The problem I'm currently encountering is that I don't see any files that can be overwritten.Thanks!

My settings.yml:
```
security:
  enableLogin: false # set to 'true' to enable login
  initialLogin:
    username: 'username' # Specify the initial username for first boot (e.g. 'admin')
    password: 'password' # Specify the initial password for first boot (e.g. 'password123')
  csrfDisabled: true

system:
  defaultLocale: 'de-DE' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  customStaticFilePath: '/customFiles/static/' # Directory path for custom static files

#ui:
  appName: Nukular PDF # Application's visible name
  homeDescription: Nukular helps you editing your PDFs # Short description or tagline shown on homepage.
  appNameNavbar: Nukular PDF # Name displayed on the navigation bar

endpoints:
  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: true # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable
```

My docker-compose.yml
```
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '22111:8080'
    volumes:
      - ./location/of/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./location/of/extraConfigs:/configs
      - ./location/of/customFiles:/customFiles/
      - ./location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false 
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false 
      - LANGS=zh_CN 
```
