### ISSUE TITLE
OAuth2 / OIDC login seems not working properly

### ISSUE THREAD

**Issue by harwck** [Stirling-Tools/Stirling-PDF#1197]
I try to use Auth0 for OIDC login and it doesn't seem to be working for me:
I didn't see a button saying `Login via Single Sign-on` on the Sign-in page as shown in this PR:

https://github.com/Stirling-Tools/Stirling-PDF/pull/1140

Will appreciate your help if anyone found something is wrong with my config

Below is my configuration:

```yaml
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -q 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    logging:
      driver: journald
    ports:
      - '127.0.0.1:8011:8080'
    volumes:
      - ./config:/configs
      - ./logs:/logs
      # - /location/of/trainingData:/usr/share/tessdata #Required for extra OCR languages
      # - /location/of/customFiles:/customFiles/
      # - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLELOGIN=true
      - SECURITY_OAUTH2_ENABLED=true
      # This is set to true to allow auto-creation of non-existing users in Striling-PDF
      - SECURITY_OAUTH2_AUTOCREATEUSER=true
      # Change with any other provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) end-point
      - SECURITY_OAUTH2_ISSUER=https://****.jp.auth0.com
      # Client ID from your provider
      - SECURITY_OAUTH2_CLIENTID=******************
      # Client Secret from your provider
      - SECURITY_OAUTH2_CLIENTSECRET=************************
      - PUID=1002
      - PGID=1002
      - UMASK=022
      - SYSTEM_DEFAULTLOCALE=en-US
      - UI_APPNAME=Stirling-PDF
      - UI_HOMEDESCRIPTION=Stirling-PDF self hosted
      - UI_APPNAMENAVBAR=Stirling-PDF
      - SYSTEM_MAXFILESIZE=100
      - METRICS_ENABLED=true
      - SYSTEM_GOOGLEVISIBILITY=false

    restart: on-failure:5


```
