### ISSUE TITLE
Could not pass bookAndHtmlFormatsInstalled setting

### ISSUE THREAD

**Issue by 11laflame** [Stirling-Tools/Stirling-PDF#1212]
none of these configurations(through settings.yml and envs) couldn't apply setting that you mentioned in documentation
(Requires bookAndHtmlFormatsInstalled flag and Calibre installed) 

settings.yml :

```

system:
  customApplications:
    bookAndHtmlFormatsInstalled: true
```
    
docker-compose.yml:

```
version: "3.1"

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - /location/of/trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - /src/lib/stirling-config:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SYSTEM_CUSTOM_APPLICATIONS_BOOK_AND_HTML_FORMATS_INSTALLED=true
    restart: always
```
