### ISSUE TITLE
Trouble using Google Auth for login, possibly scope error

### ISSUE THREAD

**Issue by avicoder** [Stirling-Tools/Stirling-PDF#1258]
Hi
Thanks for creating this tool.

I am currently setting up the login page for accessing my self-hosted instance of this PDF tool.

This is the docker-compose file

```
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
      - ./customFiles:/customFiles/
      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
      - SECURITY_ENABLE_LOGIN=true

```

This is the setting.yaml

```
# Welcome to settings file
# Remove comment marker # if on start of line to enable the configuration
# If you want to override with environment parameter follow parameter naming SECURITY_INITIALLOGIN_USERNAME

security:
  enableLogin: true # set to 'true' to enable login
  csrfDisabled: true # Set to 'true' to disable CSRF protection (not recommended for production)
  loginAttemptCount: 5 # lock user account after 5 tries
  loginResetTimeMinutes : 120 # lock account for 2 hours after x attempts
#  initialLogin:
#    username: "admin" # Initial username for the first login
#    password: "stirling" # Initial password for the first login
  oauth2:
    enabled: true # set to 'true' to enable login (Note: enableLogin must also be 'true' for this to work)
    issuer: "https://accounts.google.com" # set to any provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) end-point
    clientId: "<>.apps.googleusercontent.com" # Client ID from your provider
    clientSecret: "<>" # Client Secret from your provider
    autoCreateUser: true # set to 'true' to allow auto-creation of non-existing users
    useAsUsername: "email" # Default is 'email'; custom fields can be used as the username
    scopes: "openid, profile, email" # Specify the scopes for which the application will request permissions
    provider: "google" # Set this to your OAuth provider's name, e.g., 'google' or 'keycloak'

system:
  defaultLocale: 'en-US' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # Set to enable functionality which might need more testing before it fully goes live (This feature might make no changes)
  showUpdate: true # see when a new update is available
  showUpdateOnlyAdmin: true # Only admins can see when a new update is available, depending on showUpdate it must be set to 'true'
  customHTMLFiles: false # enable to have files placed in /customFiles/templates override the existing template html files

ui:
  appName: PDF Tool # Application's visible name
  homeDescription: null # Short description or tagline shown on homepage.
  appNameNavbar: null # Name displayed on the navigation bar

endpoints:
  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: false # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable

# Automatically Generated Settings (Do Not Edit Directly)
AutomaticallyGenerated:
  key: 2c6eff87-fc92-41e8-bc32-bd90b4bcf154

```

However on the login page I am encountering an error: 

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/2093260/21097819-22c1-4cf9-841b-daa19c07b409)

Digging furhter , I think it has to do with the scope not getting funnelled properly in the backed, this is the similar  issue I stumbled on. - https://github.com/spring-projects/spring-security/issues/10143

this is the docker compose log
```
stirling-pdf-1  | 07:15:23.962 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
stirling-pdf-1  | 07:15:23.992 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port 8080 (http) with context path ''
stirling-pdf-1  | 07:15:24.029 [main] INFO  s.software.SPDF.SPdfApplication - Started SPdfApplication in 17.467 seconds (process running for 18.901)
stirling-pdf-1  | 07:15:25.182 [main] INFO  s.software.SPDF.SPdfApplication - Stirling-PDF Started.
stirling-pdf-1  | 07:15:25.185 [main] INFO  s.software.SPDF.SPdfApplication - Navigate to http://localhost:8080
stirling-pdf-1  | 07:15:26.246 [http-nio-8080-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
stirling-pdf-1  | 07:15:26.247 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
stirling-pdf-1  | 07:15:26.250 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Completed initialization in 3 ms
stirling-pdf-1  | 07:15:43.823 [http-nio-8080-exec-5] ERROR s.s.S.c.s.CustomAuthenticationFailureHandler - Failed login attempt from IP:
stirling-pdf-1  | 07:15:56.151 [http-nio-8080-exec-2] ERROR s.s.S.c.s.o.CustomOAuth2UserService - Unexpected error loading OIDC user
stirling-pdf-1  | java.lang.NullPointerException: Cannot invoke "org.springframework.security.oauth2.core.oidc.OidcUserInfo.getClaimAsString(String)" because the return value of "org.springframework.security.oauth2.core.oidc.user.OidcUser.getUserInfo()" is null
stirling-pdf-1  |       at stirling.software.SPDF.config.security.oauth2.CustomOAuth2UserService.loadUser(CustomOAuth2UserService.java:48)
stirling-pdf-1  |       at stirling.software.SPDF.config.security.oauth2.CustomOAuth2UserService.loadUser(CustomOAuth2UserService.java:21)
stirling-pdf-1  |       at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.authenticate(OidcAuthorizationCodeAuthenticationProvider.java:158)
stirling-pdf-1  |       at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
stirling-pdf-1  |       at org.springframework.security.authentication.ObservationAuthenticationManager.lambda$authenticate$1(ObservationAuthenticationManager.java:54)
stirling-pdf-1  |       at io.micrometer.observation.Observation.observe(Observation.java:565)
stirling-pdf-1  |       at org.springframework.security.authentication.ObservationAuthenticationManager.authenticate(ObservationAuthenticationManager.java:53)
stirling-pdf-1  |       at org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter.attemptAuthentication(OAuth2LoginAuthenticationFilter.java:196)
stirling-pdf-1  |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231)
stirling-pdf-1  |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:181)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
stirling-pdf-1  |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
stirling-pdf-1  |       at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
stirling-pdf-1  |       at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
stirling-pdf-1  |       at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
stirling-pdf-1  |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
stirling-pdf-1  |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
stirling-pdf-1  |       at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
stirling-pdf-1  |       at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
stirling-pdf-1  |       at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
stirling-pdf-1  |       at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
stirling-pdf-1  |       at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
stirling-pdf-1  |       at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
stirling-pdf-1  |       at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
stirling-pdf-1  |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
stirling-pdf-1  |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
stirling-pdf-1  |       at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
stirling-pdf-1  |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
stirling-pdf-1  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
stirling-pdf-1  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
stirling-pdf-1  |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
stirling-pdf-1  |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
stirling-pdf-1  |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
stirling-pdf-1  |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
stirling-pdf-1  |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
stirling-pdf-1  |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
stirling-pdf-1  |       at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:735)
stirling-pdf-1  |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
stirling-pdf-1  |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
stirling-pdf-1  |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
stirling-pdf-1  |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
stirling-pdf-1  |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
stirling-pdf-1  |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
stirling-pdf-1  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
stirling-pdf-1  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
stirling-pdf-1  |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
stirling-pdf-1  |       at java.base/java.lang.Thread.run(Thread.java:1583)
stirling-pdf-1  | 07:15:56.158 [http-nio-8080-exec-2] ERROR s.s.S.c.s.o.CustomOAuth2AuthenticationFailureHandler - OAuth2 Authentication error: Unexpected error during authentication

```

Thanks

**Comment by Ludy87** [comment]
I'm not sure, but the scopes for Google are: `"https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile, OpenID"`

**Comment by avicoder** [comment]
yeah, correct -all these already exists in the Oauth concent screen
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/2093260/69305b24-dbac-4d75-af92-4eda44575a99)

**Comment by Ludy87** [comment]
```
# Welcome to settings file
# Remove comment marker # if on start of line to enable the configuration
# If you want to override with environment parameter follow parameter naming SECURITY_INITIALLOGIN_USERNAME

security:
  enableLogin: true # set to 'true' to enable login
  csrfDisabled: true # Set to 'true' to disable CSRF protection (not recommended for production)
  loginAttemptCount: 5 # lock user account after 5 tries
  loginResetTimeMinutes : 120 # lock account for 2 hours after x attempts
#  initialLogin:
#    username: "admin" # Initial username for the first login
#    password: "stirling" # Initial password for the first login
  oauth2:
    enabled: true # set to 'true' to enable login (Note: enableLogin must also be 'true' for this to work)
    issuer: "https://accounts.google.com" # set to any provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) end-point
    clientId: "<>.apps.googleusercontent.com" # Client ID from your provider
    clientSecret: "<>" # Client Secret from your provider
    autoCreateUser: true # set to 'true' to allow auto-creation of non-existing users
    useAsUsername: "email" # Default is 'email'; custom fields can be used as the username
    scopes: "https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile, OpenID" # Specify the scopes for which the application will request permissions
    provider: "google" # Set this to your OAuth provider's name, e.g., 'google' or 'keycloak'

system:
  defaultLocale: 'en-US' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # Set to enable functionality which might need more testing before it fully goes live (This feature might make no changes)
  showUpdate: true # see when a new update is available
  showUpdateOnlyAdmin: true # Only admins can see when a new update is available, depending on showUpdate it must be set to 'true'
  customHTMLFiles: false # enable to have files placed in /customFiles/templates override the existing template html files

ui:
  appName: PDF Tool # Application's visible name
  homeDescription: null # Short description or tagline shown on homepage.
  appNameNavbar: null # Name displayed on the navigation bar

endpoints:
  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: false # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable

# Automatically Generated Settings (Do Not Edit Directly)
AutomaticallyGenerated:
  key: 2c6eff87-fc92-41e8-bc32-bd90b4bcf154

```

That's how it should be
