### ISSUE TITLE
Login with Single-Sign On: always OpenID connect

### ISSUE THREAD

**Issue by Kofl** [Stirling-Tools/Stirling-PDF#1367]
Hi,

I upgraded to 0.25.1 and the Single Sign-On now always show to click "OpenID connect":

![OpenIDPrompt](https://github.com/Stirling-Tools/Stirling-PDF/assets/6079097/a7dcd3d6-f377-421e-8d10-e464106517a6)

Shouldn't it show the OAuth provider name instead of just OpenID, thats rather confusing for the end users.

Thanks,
Thomas

```
version: '3.3'
services:
  stirling-pdf:
    container_name: Stirling-PDF-Security
    image: frooodle/s-pdf:latest
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -q 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - 8087:8080
    volumes:
      - /opt/docker/stirling/data:/usr/share/tessdata:rw
      - /opt/docker/stirling/config:/configs:rw
      - /opt/docker/stirling/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "true"
      SECURITY_ENABLELOGIN: "true"
      SECURITY_OAUTH2_ENABLED: "true"
      SECURITY_OAUTH2_AUTOCREATEUSER: "true" # This is set to true to allow auto-creation of non-existing users in Striling-PDF
      SECURITY_OAUTH2_ISSUER: xx
      SECURITY_OAUTH2_CLIENTID: xx
      SECURITY_OAUTH2_CLIENTSECRET:  xx
      SECURITY_OAUTH2_USEASUSERNAME: "email"
      SECURITY_OAUTH2_SCOPES: "openid, profile, email"
      SECURITY_OAUTH2_PROVIDER: "Office365"
      PUID: 1002
      PGID: 1002
      UMASK: "022"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling-PDF
      UI_APPNAMENAVBAR: Stirling-PDF Latest
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "false"
      restart: on-failure:5
```
