### ISSUE TITLE
unable to open pdf in view-pdf

### ISSUE THREAD

**Issue by nmersi** [Stirling-Tools/Stirling-PDF#1375]
Surely I'm doing something wrong but I cannot find what.
I'm using docker to deploy stirlingpdf. The image is frooodle/s-pdf:latest
If I choose "View PDF" i'm not able to open any file, I cannot find hou pdf to be viewed/annotated are opened. The function high on the right (open file) do not work.

Thank you

the docker-compose.yml file is the following:
```
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    ports:
      - '8888:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
      - ./customFiles:/customFiles/
      - ./trainingData:/usr/share/tessdata
#      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - ENDPOINTS_TO_REMOVE=cert-sign,remove-cert-sign,change-permissions
      - UI_APP_NAME=PDF Tools
      - UI_HOME_DESCRIPTION=Comune di Sesto Fiorentino Tools per la manipolazione PDF
      - UI_APP_NAVBAR_NAME=Stirling PDF
      - LANGS=it_IT
```
