### ISSUE TITLE
Problem while adding a new user with using subdirectory (nginx proxy pass)

### ISSUE THREAD

**Issue by BartoszBrodnicki** [Stirling-Tools/Stirling-PDF#1379]
```
version: '3.3'
services:
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf:latest
    ports:
      - '7700:8080'
    volumes:
      - /data/stirling-pdf/trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - /data/stirling-pdf/configs:/configs
      - /data/stirling-pdf/customFiles:/customFiles/
      - /data/stirling-pdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLELOGIN=true
      - SYSTEM_DEFAULTLOCALE=pl-PL
      - SYSTEM_ROOTURIPATH= /pdf
```

This work perfect with custom subdirectory like domain.com/pdf, but issue is when try add new user.  When I add a new user path changes to `domain.com/api/v1/user/admin/saveUser` so its totally skip `/pdf`. I don't know if I'm doing something wrong, but currently the only solution is to **remove rooturipath**, add users using direct ip with port and after adding them again put docker with **rooturipath /pdf**.
