### ISSUE TITLE
[Bug]: ??Claim 'email' cannot be null or empty_en_US??

### ISSUE THREAD

**Issue by ivoarch** [Stirling-Tools/Stirling-PDF#2544]
### Installation Method

Docker

### The Problem

Hi, after setup and install via docker compose + Oauth2  I try to login but I get this msg "??Claim 'email' cannot be null or empty_en_US??"

### Version of Stirling-PDF

latest

### Docker Configuration

```txt
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8989:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
      - ./customFiles:/customFiles/
      - ./logs:/logs/
    environment:
        DOCKER_ENABLE_SECURITY: true
        SECURITY_ENABLELOGIN: true #or false
        SECURITY_OAUTH2_ENABLED: true
        SECURITY_OAUTH2_AUTOCREATEUSER: true # This is set to true to allow auto-creation of non-existing users in Striling-PDF
        SECURITY_OAUTH2_ISSUER: ""
        SECURITY_OAUTH2_CLIENTID: ""
        SECURITY_OAUTH2_CLIENTSECRET: ""
        SECURITY_LOGINMETHOD: "oauth2"
#        SECURITY_OAUTH2_SCOPES: "openid, profile, email"
        LANGS: en_US
        SECURITY_OAUTH2_PROVIDER: "OAuth2"
        INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
#        SYSTEM_DEFAULTLOCALE: en_GB
        UI_APPNAME: "Stirling-PDF"
        UI_APPNAMENAVBAR: "Stirling-PDF Latest"
        SYSTEM_MAXFILESIZE: 100
        SYSTEM_GOOGLEVISIBILITY: false
restart: on-failure:5
```

### Relevant Log Output

```txt
2024-12-22T12:40:00.867179399Z  at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-22T12:40:00.867181663Z Caused by: java.lang.IllegalArgumentException: Claim 'email' cannot be null or empty
2024-12-22T12:40:00.867183996Z  at stirling.software.SPDF.config.security.oauth2.CustomOAuth2UserService.loadUser(CustomOAuth2UserService.java:63)
2024-12-22T12:40:00.867186240Z  ... 95 common frames omitted
```

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment]
If you want to use OAuth2, you have to provide all the information.

```yaml
 SECURITY_OAUTH2_ENABLED: true
 SECURITY_OAUTH2_AUTOCREATEUSER: true # This is set to true to allow auto-creation of non-existing users in Striling-PDF
 SECURITY_OAUTH2_ISSUER: ""
 SECURITY_OAUTH2_CLIENTID: ""
 SECURITY_OAUTH2_CLIENTSECRET: ""
 SECURITY_LOGINMETHOD: "oauth2"
 SECURITY_OAUTH2_SCOPES: "openid, profile, email"
 SECURITY_OAUTH2_PROVIDER: "OAuth2"
```
