### ISSUE TITLE
[Bug]: UI for the table in Admin User Control Settings overflows for small-width devices

### ISSUE THREAD

**Issue by nktnet1** [Stirling-Tools/Stirling-PDF#2621]
### Installation Method

Docker

### The Problem

See below:

![image](https://github.com/user-attachments/assets/8f507fa2-de94-4e1b-9ddf-78f2aa0a7f48)

### Version of Stirling-PDF

0.36.6

### Page Where the Problem Occurred

http://localhost:8080/addUsers

### Docker Compose

```yaml
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - 50000:8080
    volumes:
      - stirling_pdf_trainingdata:/usr/share/tessdata
      - stirling_pdf_extraconfigs:/configs
      - stirling_pdf_customfiles:/customFiles/
      - stirling_pdf_logs:/logs/
      - stirling_pdf_pipeline:/pipeline/
    environment:
      DOCKER_ENABLE_SECURITY: true   # need this env to have auth/users
      SECURITY_ENABLE_LOGIN: true    # need this env to have auth/users

volumes:
  stirling_pdf_trainingdata:
  stirling_pdf_extraconfigs:
  stirling_pdf_customfiles:
  stirling_pdf_logs:
  stirling_pdf_pipeline:
```

### Browsers Affected

Firefox, Chrome, Safari, Microsoft Edge

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.
