### ISSUE TITLE
[Feature Request]: Improve Documentation on SSO

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2715]
### Feature Description

Improve docs on SSO to show example configuration for keycloak, authentik , and okta etc

Examples for authentik

```
 issuer: http://192.168.1.133:9000/application/o/stirlingpdf/ # set to any provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) end-point
    clientId: 5ibI9L0 # Client ID from your provider
    clientSecret: DFSD3B7MKLkWuEAasxxm2hghuzulPr37jdkrojPsGBz9MGwkfc # Client Secret from your provider
    autoCreateUser: true # set to 'true' to allow auto-creation of non-existing users
    blockRegistration: false # set to 'true' to deny login with SSO without prior registration by an admin
    useAsUsername: email # Default is 'email'; custom fields can be used as the username
    scopes: openid, profile, email # Specify the scopes for which the application will request permissions
    provider: authentik # Set this to your OAuth provider's name, e.g., 'google' or 'keycloak'
```	
```
  saml2:
    enabled: true # currently in alpha, not recommended for use yet, enableAlphaFunctionality must be set to true
    autoCreateUser: true # set to 'true' to allow auto-creation of non-existing users
    blockRegistration: false # set to 'true' to deny login with SSO without prior registration by an admin
    registrationId: stirling
    idpMetadataUri: http://192.168.1.133:9000/application/saml/stirlingpdf/metadata/
    idpSingleLogoutUrl: http://192.168.1.133:9000/application/saml/stirlingpdf/slo/binding/post/
    idpSingleLoginUrl: http://192.168.1.133:9000/application/saml/stirlingpdf/sso/binding/post/
    idpIssuer: authentik
    privateKey: C:/Users/systo/git/Stirling-PDF/private_key.pem
    spCert: C:/Users/systo/git/Stirling-PDF/certificate.pem
    idpCert: C:/Users/systo/git/Stirling-PDF/certificate.pem
```
	
Must show screenshots of setup in SSO app as well

### No Duplicate of the Feature

- [x] I have verified that there are no existing features requests similar to my request.
