### ISSUE TITLE
[Bug]: Docker latest and latest-fat crash when trying to connect to LibreOffice for unoconvert

### ISSUE THREAD

**Issue by nepomuc** [Stirling-Tools/Stirling-PDF#3030]
### Installation Method

Docker fat

### The Problem

Tried it with both: latest and latest-fat, following https://docs.stirlingpdf.com/Installation/Docker%20Install .
Both crash at the same point:

```
stirling-pdf-1  | Copying original files without overwriting existing files
stirling-pdf-1  | Installing font package: font-noto
stirling-pdf-1  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz
stirling-pdf-1  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz
stirling-pdf-1  | fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
stirling-pdf-1  | fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
stirling-pdf-1  | fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
stirling-pdf-1  | OK: 1665 MiB in 396 packages
stirling-pdf-1  | Setting permissions and ownership for necessary directories...
stirling-pdf-1  | Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions     -XX:MaxRAMPercentage=75     -XX:InitiatingHeapOccupancyPercent=20     -XX:+G1PeriodicGCInvokesConcurrent     -XX:G1PeriodicGCInterval=10000     -XX:+UseStringDeduplication     -XX:G1PeriodicGCSystemLoadThreshold=70
stirling-pdf-1  | INFO:unoserver:Starting unoserver 3.1.
stirling-pdf-1  | INFO:unoserver:Command: /usr/bin/soffice --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmpgszb93ss --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
stirling-pdf-1  | 02:31:51.019 [main] INFO  s.s.SPDF.config.ConfigInitializer - Created settings file from template
stirling-pdf-1  | 02:31:51.027 [main] INFO  s.software.SPDF.SPDFApplication - Settings file: ./configs/settings.yml
stirling-pdf-1  | INFO:unoserver:Starting UnoConverter.
stirling-pdf-1  | Exception in thread Thread-1 (serve):
stirling-pdf-1  | Traceback (most recent call last):
stirling-pdf-1  |   File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
stirling-pdf-1  |     self.run()
stirling-pdf-1  |   File "/usr/lib/python3.12/threading.py", line 1012, in run
stirling-pdf-1  |     self._target(*self._args, **self._kwargs)
stirling-pdf-1  |   File "/opt/venv/lib/python3.12/site-packages/unoserver/server.py", line 131, in serve
stirling-pdf-1  |     self.conv = converter.UnoConverter(
stirling-pdf-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^
stirling-pdf-1  |   File "/opt/venv/lib/python3.12/site-packages/unoserver/converter.py", line 77, in __init__
stirling-pdf-1  |     self.context = self.resolver.resolve(
stirling-pdf-1  |                    ^^^^^^^^^^^^^^^^^^^^^^
stirling-pdf-1  | unoserver.converter.com.sun.star.connection.NoConnectException: Connector : couldn't connect to socket (Connection refused) at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.6.7.2/io/source/connector/connector.cxx:118
stirling-pdf-1  | INFO:unoserver:Failed to start servers
stirling-pdf-1 exited with code 2
```

### Version of Stirling-PDF

latest available

### Docker Configuration

```txt
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    ports:
      - '8080:8080'
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
```

### Relevant Log Output

```txt

```

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

**Comment by naaru-s** [comment]
Have the same issue. Probably relative to this commit : 69da443
Last working docker tag : 0.41.0

**Comment by codenamek83** [comment]
I encountered the same issue as reported. Reverting to version 0.41.0, as suggested by @naaru-s , resolved the problem.

**Comment by Frooodle** [comment]
Will likely see the same in latest 0.43.0 Will look into cause of issue, we don't see this on our side, is there something unique about your installation? 
ARM, custom network / user etc

**Comment by nepomuc** [comment]
@Frooodle I'm running Docker inside an unprivileged Linux container. That's the only special thing I can think of for my setup.

**Comment by codenamek83** [comment]
@Frooodle I'm running the container on a Raspberry Pi 4. It's a straightforward setup with nothing unique.

`services:
  stirlingpdf01:
    image: ${IMAGE_SG_STIRLINGPDF01}
    container_name: stirlingpdf01
    hostname: stirlingpdf01
    networks:
      - stirlingpdf01
    ports:
      - '[Redacted]:8080'
    volumes:
      - /stirlingpdf01stirlingpdf01/trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - /stirlingpdf01stirlingpdf01/extraConfigs:/configs
      - /stirlingpdf01stirlingpdf01/customFiles:/customFiles
    environment:
      TZ: Asia/[Redacted]
      PUID: 1000
      PGID: 1000
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: 'PDF Tools' # application's visible name
      UI_HOMEDESCRIPTION: 'Your locally hosted one-stop-shop for all your PDF needs.' # short description or tagline shown on the homepage
      UI_APPNAMENAVBAR: 'PDF Tools' # name displayed on the navigation bar      
      SYSTEM_GOOGLEVISIBILITY: false
      DOCKER_ENABLE_SECURITY: true
      SECURITY_ENABLELOGIN: true
      SECURITY_LOGINMETHOD: oauth2
      SECURITY_OAUTH2_ENABLED: true
      SECURITY_OAUTH2_AUTOCREATEUSER: true
      SECURITY_OAUTH2_ISSUER: "[Redacted]"
      SECURITY_OAUTH2_CLIENTID: "stirling-pdf"
      SECURITY_OAUTH2_CLIENTSECRET: "[Redacted]"
      SECURITY_OAUTH2_USEASUSERNAME: "preferred_username"
      SECURITY_OAUTH2_SCOPES: "openid,profile,email"
      SECURITY_OAUTH2_PROVIDER: Authelia
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # Limit to 75% of a single CPU
    cpu_period: 100000  # 100ms
    cpu_quota: 75000    # Allow 75ms CPU time per 100ms period (75%)
    # Pin to specific CPU cores to reduce contention
    cpuset: "0,1"       # Allow usage of CPU cores 0 and 1
    # Memory limit (optional, to avoid excessive RAM usage)
    mem_limit: "1g"     # Limit to 1GB RAM      

networks:
  stirlingpdf01:
    name: stirlingpdf01
    driver: bridge`

**Comment by foucaude** [comment]
Same problem here

```yaml
services:
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:0.43.1
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
    volumes:
      - stirling-trainingdata:/usr/share/tessdata
      - stirling-extraconfigs:/configs
      - stirling-customfiles:/customFiles/
      - stirling-logs:/logs/
      - stirling-pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=fr_FR

networks:
  web:
    name: web
    external: true

volumes:
  stirling-trainingdata:
    name: stirling-trainingdata
  stirling-extraconfigs:
    name: stirling-extraconfigs
  stirling-customfiles:
    name: stirling-customfiles
  stirling-logs:
    name: stirling-logs
  stirling-pipeline:
    name: stirling-pipeline
```

**Comment by Frooodle** [comment]
For users seeing the issue could you try run 
``ghcr.io/unoconv/unoserver-docker`` with port ``2003`` with similar network configuration and see if that works?

Would love to see if its a unoserver issue or not

**Comment by lcd4linux** [comment]
> For users seeing the issue could you try run the docker `ghcr.io/unoconv/unoserver-docker` with port `2003` with similar network configuration and see if that works?
> 
> Would love to see if its a unoserver issue or not

This is the log, container starts up

`using: LibreOffice 7.6.7.2 60(Build:2)

Running unoserver-docker in non-interactive.

For interactive mode use '-it', e.g. 'docker run -v /tmp:/data -it unoserver/unoserver-docker'.

INFO:unoserver:Starting unoserver 3.0.1.



server:Command: /usr/bin/soffice --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmpoanyhsu2 --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext

INFO:unoserver:Starting UnoConverter.

INFO:unoserver:Starting UnoComparer.

INFO:unoserver:Server PID: 22`

**Comment by lcd4linux** [comment]
> [@lcd4linux](https://github.com/lcd4linux) can you confirm your compose file for you starting this?

Yes, but no Stirling Website of course.

**Comment by alex3305** [comment]
> For users seeing the issue could you try run the docker `ghcr.io/unoconv/unoserver-docker` with port `2003` with similar network configuration and see if that works?
> 
> Would love to see if its a unoserver issue or not

Sure. Thanks for taking the time to respond ❤ . I tried it with this Docker Compose:

```yaml
services:
  unoserver-test:
    container_name: unoserver-test
    image: ghcr.io/unoconv/unoserver-docker
    restart: on-failure
    networks:
      ingress: null
    cpuset: "19"
    cpus: 0.5
    labels:
      - caddy=*.example.com
      - caddy.@unoserver-test.host=unoserver.example.com
      - caddy.handle=@unoserver-test
      - caddy.handle.reverse_proxy={{upstreams 2003}}

networks:
  ingress:
    name: swarm-overlay
    external: true
```

Which seems to work:

```
using: LibreOffice 7.6.7.2 60(Build:2)
Running unoserver-docker in non-interactive.
For interactive mode use '-it', e.g. 'docker run -v /tmp:/data -it unoserver/unoserver-docker'.
INFO:unoserver:Starting unoserver 3.0.1.
INFO:unoserver:Command: /usr/bin/soffice --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmp_i_ljuw5 --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
INFO:unoserver:Starting UnoConverter.
INFO:unoserver:Starting UnoComparer.
INFO:unoserver:Server PID: 22
10.0.4.185 - - [28/Feb/2025 19:15:04] code 501, message Unsupported method ('GET')
10.0.4.185 - - [28/Feb/2025 19:15:04] "GET / HTTP/1.1" 501 -
10.0.4.185 - - [28/Feb/2025 19:15:05] code 501, message Unsupported method ('GET')
10.0.4.185 - - [28/Feb/2025 19:15:05] "GET /favicon.ico HTTP/1.1" 501 -
```

![Image](https://github.com/user-attachments/assets/fd09bf4b-5732-4f67-b7aa-38e9aab3cbfb)

The container stays up perfectly fine. Even after a couple of minutes.

**Comment by Frooodle** [comment]
Interesting 🤔 
Will be looking into this tonight 
Thanks for the research

**Comment by Frooodle** [comment]
For users facing this issue I recommend using v0.41.0 in meantime

**Comment by r0ckarong** [comment]
(On Synology) Just tried going from my latest:ultra-lite to something with authentication so I rolled out latest:fat and experienced the same problem. Works just fine with the suggested 0.41.0.

**Comment by r0ckarong** [comment]
(On Synology) Just tried going from my latest:ultra-lite to something with authentication so I rolled out latest:fat and experienced the same problem. Works just fine with the suggested 0.41.0.

compose.yml
```yaml
services:
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:0.41.0-fat
    ports:
      - '9999:8080'
    volumes:
      #- ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./configs/:/configs
      #- ./customFiles:/customFiles/
      - ./logs:/logs/
      #- ./pipeline:/pipeline/
    environment:
      - PUID=<REDACTED>
      - PGID=<REDACTED>
      - LANGS=en_US
      - DOCKER_ENABLE_SECURITY=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - SECURITY_ENABLE_LOGIN=true
      - SECURITY_INITIALLOGIN_USERNAME=<REDACTED>
      - SECURITY_INITIALLOGIN_PASSWORD=<REDACTED>
    network_mode: synobridge
```
