### ISSUE TITLE
[Bug]: image 0.43.0 not loading app

### ISSUE THREAD

**Issue by ivancarlosti** [Stirling-Tools/Stirling-PDF#3064]
### Installation Method

Docker

### The Problem

Got this error running my docker compose, it was running fine until previous version, the application do not load, the docker keeps running:

```
00:07:49.559 [main] INFO  s.software.SPDF.SPDFApplication - Custom settings file: ./configs/custom_settings.yml
pdf  | 00:07:50.973 [main] ERROR o.s.boot.SpringApplication - Application run failed
pdf  | org.yaml.snakeyaml.constructor.ConstructorException: while constructing an int
pdf  |  in 'reader', line 98, column 11:
pdf  |         port: !!int '' # set the port number o ...
pdf  |               ^
pdf  | found empty value
pdf  |  in 'reader', line 98, column 11:
pdf  |         port: !!int '' # set the port number o ...
pdf  |               ^
pdf  |
pdf  |  at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlInt.construct(SafeConstructor.java:257)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247)
pdf  |  at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.constructObject(OriginTrackedYamlLoader.java:113)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576)
pdf  |  at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552)
pdf  |  at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247)
pdf  |  at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.constructObject(OriginTrackedYamlLoader.java:119)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576)
pdf  |  at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552)
pdf  |  at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247)
pdf  |  at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.constructObject(OriginTrackedYamlLoader.java:119)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576)
pdf  |  at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552)
pdf  |  at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247)
pdf  |  at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.constructObject(OriginTrackedYamlLoader.java:119)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:201)
pdf  |  at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:166)
pdf  |  at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99)
pdf  |  at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:529)
pdf  |  at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:203)
pdf  |  at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:169)
pdf  |  at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
pdf  |  at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
pdf  |  at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:54)
pdf  |  at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:36)
pdf  |  at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:96)
pdf  |  at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
pdf  |  at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
pdf  |  at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:121)
pdf  |  at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:245)
pdf  |  at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
pdf  |  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
pdf  |  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
pdf  |  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:132)
pdf  |  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:115)
pdf  |  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
pdf  |  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
pdf  |  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
pdf  |  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
pdf  |  at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
pdf  |  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
pdf  |  at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
pdf  |  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
pdf  |  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
pdf  |  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
pdf  |  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
pdf  |  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:353)
pdf  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
pdf  |  at stirling.software.SPDF.SPDFApplication.main(SPDFApplication.java:125)
pdf  |  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
pdf  |  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
pdf  |  at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)
pdf  |  at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)
pdf  |  at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)
pdf  | INFO:unoserver:Starting UnoConverter.
pdf  | INFO:unoserver:Starting UnoComparer.

```

### Version of Stirling-PDF

0.43.0

### Last Working Version of Stirling-PDF

0.42.0

### Docker Configuration

```txt
name: pdf

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: pdf
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - '8020:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
      - ./customFiles:/customFiles
      - ./logs:/logs
    environment:
      DOCKER_ENABLE_SECURITY: "true"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: "Faz-tudo com PDF"
      UI_HOMEDESCRIPTION: "Editor de PDF seguro pelo navegador."
      UI_APPNAMENAVBAR: "Faz-tudo com PDF"
      SYSTEM_MAXFILESIZE: "25"
      SYSTEM_GOOGLEVISIBILITY: "true"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```

### Relevant Log Output

```txt

```

### Additional Information

I suggest to open a new tag called "stable" and run previous version for some days instead of pulling latest released image on same day of it's release date

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Thanks will raising will change latest tag to 0.43.0 while we investigate the issue

**Comment by ivancarlosti** [comment]
I recreated my custom_settings as @dosubot recomended and worked fine, some information there was not accepted by the ney image :/

**Comment by Frooodle** [comment]
Do you have any idea about what info that is? could you share to help others?

**Comment by Frooodle** [comment]
I cant reproduce the issue my side so hard to tell..
looking at
port: !!int '' # set the port number o ..

it says your port number wasn't a integer

**Comment by Frooodle** [comment]
For anyone else facing this issue, please check if your yaml is correctly formatted, welcome to post here for advice

**Comment by ivancarlosti** [comment]
For some reason my custom settings was empty, and there was my settings.yml until today morning from my backup:

settings.yml
```
#############################################################################################################
#                                         Welcome to settings file from                                     #
#                      ____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____                   #
#                     / ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|                  #
#                     \___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_                     #
#                      ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|                    #
#                     |____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|                      #
#                                                                                                           #
# Do not comment out any entry, it will be removed on next startup                                          #
# If you want to override with environment parameter follow parameter naming SECURITY_INITIALLOGIN_USERNAME #
#############################################################################################################


security:
  enableLogin: true # set to 'true' to enable login
  csrfDisabled: false # set to 'true' to disable CSRF protection (not recommended for production)
  loginAttemptCount: 5 # lock user account after 5 tries; when using e.g. Fail2Ban you can deactivate the function with -1
  loginResetTimeMinutes: 120 # lock account for 2 hours after x attempts
  loginMethod: normal # Accepts values like 'all' and 'normal'(only Login with Username/Password), 'oauth2'(only Login with OAuth2) or 'saml2'(only Login with SAML2)
  initialLogin:
    username: 'supressed'
    password: 'supressed'
  oauth2:
    enabled: false # set to 'true' to enable login (Note: enableLogin must also be 'true' for this to work)
    client:
      keycloak:
        issuer: '' # URL of the Keycloak realm's OpenID Connect Discovery endpoint
        clientId: '' # client ID for Keycloak OAuth2
        clientSecret: '' # client secret for Keycloak OAuth2
        scopes: openid, profile, email # scopes for Keycloak OAuth2
        useAsUsername: preferred_username # field to use as the username for Keycloak OAuth2
      google:
        clientId: '' # client ID for Google OAuth2
        clientSecret: '' # client secret for Google OAuth2
        scopes: https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile # scopes for Google OAuth2
        useAsUsername: email # field to use as the username for Google OAuth2
      github:
        clientId: '' # client ID for GitHub OAuth2
        clientSecret: '' # client secret for GitHub OAuth2
        scopes: read:user # scope for GitHub OAuth2
        useAsUsername: login # field to use as the username for GitHub OAuth2
    issuer: '' # set to any provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) endpoint
    clientId: '' # client ID from your provider
    clientSecret: '' # client secret from your provider
    autoCreateUser: false # set to 'true' to allow auto-creation of non-existing users
    blockRegistration: true # set to 'true' to deny login with SSO without prior registration by an admin
    useAsUsername: email # default is 'email'; custom fields can be used as the username
    scopes: openid, profile, email # specify the scopes for which the application will request permissions
    provider: google # set this to your OAuth provider's name, e.g., 'google' or 'keycloak'
  saml2:
    enabled: false # Only enabled for paid enterprise clients (enterpriseEdition.enabled must be true)
    autoCreateUser: false # set to 'true' to allow auto-creation of non-existing users
    blockRegistration: false # set to 'true' to deny login with SSO without prior registration by an admin
    registrationId: stirling
    idpMetadataUri: https://dev-XXXXXXXX.okta.com/app/externalKey/sso/saml/metadata
    idpSingleLogoutUrl: https://dev-XXXXXXXX.okta.com/app/dev-XXXXXXXX_stirlingpdf_1/externalKey/slo/saml
    idpSingleLoginUrl: https://dev-XXXXXXXX.okta.com/app/dev-XXXXXXXX_stirlingpdf_1/externalKey/sso/saml
    idpIssuer: http://www.okta.com/externalKey
    idpCert: classpath:octa.crt
    privateKey: classpath:saml-private-key.key
    spCert: classpath:saml-public-cert.crt

enterpriseEdition:
  enabled: false # set to 'true' to enable enterprise edition
  key: 00000000-0000-0000-0000-000000000000
  SSOAutoLogin: false # Enable to auto login to first provided SSO
  CustomMetadata:
    autoUpdateMetadata: false # set to 'true' to automatically update metadata with below values
    author: username # supports text such as 'John Doe' or types such as username to autopopulate with user's username
    creator: Stirling-PDF # supports text such as 'Company-PDF'
    producer: Stirling-PDF # supports text such as 'Company-PDF'

legal:
  termsAndConditions: https://supressed # URL to the terms and conditions of your application (e.g. https://example.com/terms). Empty string to disable or filename to load from local file in static folder
  privacyPolicy: https://supressed # URL to the privacy policy of your application (e.g. https://example.com/privacy). Empty string to disable or filename to load from local file in static folder
  accessibilityStatement: '' # URL to the accessibility statement of your application (e.g. https://example.com/accessibility). Empty string to disable or filename to load from local file in static folder
  cookiePolicy: '' # URL to the cookie policy of your application (e.g. https://example.com/cookie). Empty string to disable or filename to load from local file in static folder
  impressum: '' # URL to the impressum of your application (e.g. https://example.com/impressum). Empty string to disable or filename to load from local file in static folder

system:
  defaultLocale: en-US # set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: true # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # set to enable functionality which might need more testing before it fully goes live (this feature might make no changes)
  showUpdate: false # see when a new update is available
  showUpdateOnlyAdmin: false # only admins can see when a new update is available, depending on showUpdate it must be set to 'true'
  customHTMLFiles: false # enable to have files placed in /customFiles/templates override the existing template HTML files
  tessdataDir: /usr/share/tessdata # path to the directory containing the Tessdata files. This setting is relevant for Windows systems. For Windows users, this path should be adjusted to point to the appropriate directory where the Tessdata files are stored.
  enableAnalytics: 'true' # set to 'true' to enable analytics, set to 'false' to disable analytics; for enterprise users, this is set to true
  disableSanitize: false # set to true to disable Sanitize HTML; (can lead to injections in HTML)
  datasource:
    enableCustomDatabase: false # Enterprise users ONLY, set this property to 'true' if you would like to use your own custom database configuration
    customDatabaseUrl: # eg jdbc:postgresql://localhost:5432/postgres, set the url for your own custom database connection. If provided, the type, hostName, port and name are not necessary and will not be used
    username: # set the database username
    password: # set the database password
    type: # the type of the database to set (e.g. 'h2', 'postgresql')
    hostName: # the host name to use for the database url. Set to 'localhost' when running the app locally. Set to match the name of the container name of your database container when running the app on a server (Docker configuration)
    port: # set the port number of the database. Ensure this matches the port the database is listening to
    name: # set the name of your database. Should match the name of the database you create

ui:
  appName: Faz-tudo com PDF # application's visible name
  homeDescription: Editor de PDF seguro pelo navegador. # short description or tagline shown on the homepage
  appNameNavbar: Faz-tudo com PDF # name displayed on the navigation bar

  languages: ["en_US", "pt_BR", "es_ES"] # If empty, all languages are enabled. To display only German and Polish ["de_DE", "pl_PL"]. British English is always enabled.

endpoints:
  toRemove: [] # list endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # list groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: false # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable

# Automatically Generated Settings (Do Not Edit Directly)
AutomaticallyGenerated:
  key: supressed
  UUID: supressed
  appVersion: 0.42.0

processExecutor:
  sessionLimit: # Process executor instances limits
    libreOfficeSessionLimit: 1
    pdfToHtmlSessionLimit: 1
    qpdfSessionLimit: 4
    tesseractSessionLimit: 1
    pythonOpenCvSessionLimit: 8
    weasyPrintSessionLimit: 16
    installAppSessionLimit: 1
    calibreSessionLimit: 1
  timeoutMinutes: # Process executor timeout in minutes
    libreOfficetimeoutMinutes: 30
    pdfToHtmltimeoutMinutes: 20
    pythonOpenCvtimeoutMinutes: 30
    weasyPrinttimeoutMinutes: 30
    installApptimeoutMinutes: 60
    calibretimeoutMinutes: 30
    tesseractTimeoutMinutes: 30

```

**Comment by Frooodle** [comment]
Looks like the issue was around
```
  datasource:
    enableCustomDatabase: false # Enterprise users ONLY, set this property to 'true' if you would like to use your own custom database configuration
    customDatabaseUrl: # eg jdbc:postgresql://localhost:5432/postgres, set the url for your own custom database connection. If provided, the type, hostName, port and name are not necessary and will not be used
    username: # set the database username
    password: # set the database password
    type: # the type of the database to set (e.g. 'h2', 'postgresql')
    hostName: # the host name to use for the database url. Set to 'localhost' when running the app locally. Set to match the name of the container name of your database container when running the app on a server (Docker configuration)
    port: # set the port number of the database. Ensure this matches the port the database is listening to
    name: # set the name of your database. Should match the name of the database you create
```

Im not sure why but your config here had no values instead of defaults like
```
  datasource:
    enableCustomDatabase: false # Enterprise users ONLY, set this property to 'true' if you would like to use your own custom database configuration
    customDatabaseUrl: '' # eg jdbc:postgresql://localhost:5432/postgres, set the url for your own custom database connection. If provided, the type, hostName, port and name are not necessary and will not be used
    username: postgres # set the database username
    password: postgres # set the database password
    type: postgresql # the type of the database to set (e.g. 'h2', 'postgresql')
    hostName: localhost # the host name to use for the database url. Set to 'localhost' when running the app locally. Set to match the name of the container name of your database container when running the app on a server (Docker configuration)
    port: 5432 # set the port number of the database. Ensure this matches the port the database is listening to
    name: postgres # set the name of your database. Should match the name of the database you create
```
This may have caused the issue
