### ISSUE TITLE
[Feature Request] - Helm chart for this application

### ISSUE THREAD

**Issue by debugger24** [Stirling-Tools/Stirling-PDF#335]
Can we have a helm chart for this application so that we can directly deploy? I can help with it.

**Comment by debugger24** [comment]
Cool, I will pick this up this/next week.

**Comment by matthisholleville** [comment]
Hi there! Shouldn't we push the Helm chart? Currently, we can't use it as a Helm dependency. 

```yaml
# Example
apiVersion: v2
name: my-chart
description: my-description
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: strirling-pdf
    version: "0.1.0"
    repository: "https://github.com/Stirling-Tools/Stirling-PDF/charts"
```

We could consider using GitHub Pages to host the Helm `.tgz` file.
