### ISSUE TITLE
[Bug]: Application crashes on startup when an OAuth service is unavailable

### ISSUE THREAD

**Issue by flustosa** [Stirling-Tools/Stirling-PDF#3656]
### Installation Method

Docker

### The Problem

The application crashes during its startup sequence when one of its configured OAuth services is unavailable (e.g., returns a 502 Bad Gateway error or any 5xx error). This issue occurs even when multiple OAuth services are configured and at least one is operational.

For example, if both Google OAuth and Authentik OAuth are configured, and Authentik is unreachable or returns an error during the application's initialization, the application fails to start entirely. This prevents the application from launching, making it unusable even if other OAuth services are functional.

- Testing Scenario:

1. Configure OAuth Services: In the settings.yml file, configure one or more OAuth services.
2. Simulate Service Unavailability: Stop or disable one of the configured OAuth services (e.g., Authentik) in a way that any request to its URL returns a 5xx error (e.g., 502 Bad Gateway, 500 Internal Server Error).
3. Attempt Application Startup: Start the application's container stack.

- Expected behavior: 

The application should handle the unavailable OAuth service gracefully during startup. It should ideally start successfully, perhaps logging an error for the unavailable service, and allow users to proceed with any other available OAuth service.

- Actual behavior:

The application crashes and fails to start.

### Version of Stirling-PDF

0.46.2

### Last Working Version of Stirling-PDF

0.46.2

### Docker Configuration

```txt

```

### Relevant Log Output

```txt
stirling-pdf-1  | 17:16:10.320 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through field 'httpSecurity': Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.HttpSecurityConfiguration': Unsatisfied dependency expressed through method 'setContentNegotiationStrategy' parameter 0: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientWebMvcSecurityConfiguration': Failed to instantiate [org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientWebMvcSecurityConfiguration]: Constructor threw exception
stirling-pdf-1  | 17:16:11.496 [main] ERROR o.s.boot.SpringApplication - Application run failed
stirling-pdf-1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through field 'httpSecurity': Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.HttpSecurityConfiguration': Unsatisfied dependency expressed through method 'setContentNegotiationStrategy' parameter 0: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientWebMvcSecurityConfiguration': Failed to instantiate [org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientWebMvcSecurityConfiguration]: Constructor threw exception

stirling-pdf-1  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.HttpSecurityConfiguration': Unsatisfied dependency expressed through method 'setContentNegotiationStrategy' parameter 0: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientWebMvcSecurityConfiguration': Failed to instantiate [org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientWebMvcSecurityConfiguration]: Constructor threw exception

stirling-pdf-1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OAuth2AuthorizedClientManager': Failed to instantiate [org.springframework.security.oauth2.client.OAuth2AuthorizedClientManager]: Factory method 'getAuthorizedClientManager' threw exception with message: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [stirling/software/SPDF/config/security/oauth2/OAuth2Configuration.class]: Failed to instantiate [org.springframework.security.oauth2.client.registration.ClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception with message: Unable to resolve Configuration with the provided Issuer of "https://[AUTH.MYDOMAIN.COM]/application/o/pdf/"

stirling-pdf-1  | Caused by: org.springframework.web.client.HttpServerErrorException$BadGateway: 502 Bad Gateway on GET request for "https://[AUTH.MYDOMAIN.COM]/application/o/pdf/.well-known/openid-configuration": "error code: 502"
```

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

**Comment by CoolID2** [comment]
Hi all,

I've got the same behavior in my docker container.
Any helpful Information to fix this Issue?

Best regards

**Comment by flustosa** [comment]
Hi @CoolID2 ,

I found a workaround using Docker Compose with [autoheal](https://github.com/willfarrell/docker-autoheal) to make the startup sequence more resilient. While it doesn't fix the core application logic, it ensures the container automatically restarts until it can launch successfully.

The core idea is to use a healthcheck that verifies both Stirling PDF and its authentication provider are reachable. If the check fails, the autoheal service automatically restarts the container, creating a retry loop that resolves itself once all services are fully online.

In addition to the autoheal solution, another practice I adopted is ensuring the correct startup sequence for the services (in my case, i use separate VMs on Proxmox.

_Remember to adjust the healthcheck interval and AUTOHEAL* timers in your configuration to match your environment's specific startup speed._


```yaml
services:
  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=10
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    healthcheck:
      # This tests both the auth provider and Stirling PDF.
      # If either fails, the container is marked as unhealthy.
      test: curl --fail https://auth.example.com/-/health/live/ && curl --fail https://pdf.example.com/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
    labels:
      # This label tells Autoheal to monitor this container.
      - "autoheal=true"
    # ... other configs like ports, volumes, etc.
```
