### ISSUE TITLE
The pdf file becomes a blank file after being uploaded and then downloaded.

### ISSUE THREAD

**Issue by chj9** [Stirling-Tools/Stirling-PDF#418]
## Original file
[111.pdf](https://github.com/Frooodle/Stirling-PDF/files/12842796/111.pdf)
## Preview after uploading
Follow these steps
![image](https://github.com/Frooodle/Stirling-PDF/assets/16426260/987fa226-65b3-4486-9734-4f57774871c3)
## Preview after downloading
![image](https://github.com/Frooodle/Stirling-PDF/assets/16426260/ccc61974-11d9-4f1e-a966-b9c60d7b63d4)
## Deployment 
Centos 7
App Version: 0.14.4
docker-compose.yaml
```
version: '3.3'
services:
    s-pdf:
        ports:
            - '8080:8080'
        image: frooodle/s-pdf
```
Website access address：
http://43.159.194.123:8080/
