### ISSUE TITLE
feature request - change running port

### ISSUE THREAD

**Issue by mmomjian** [Stirling-Tools/Stirling-PDF#474]
I would prefer to run sPDF on a different port than 8080. I have tried using `command: java -Dlocal.server.port=32769 -jar /app.jar` in the docker compose, which does change the 'navigate to' message in the logs, but Tomcat still runs on 8080. Does anyone know how to change the tomcat listening port in sPDF?

**Comment by sNiXx** [comment]
Is it not sufficient to simply change the host port in the compose file? For instance:
```
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '80:8080'
    volumes:
      - /location/of/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - /location/of/extraConfigs:/configs
#      - /location/of/customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false
```
