### ISSUE TITLE
Building from Github repo

### ISSUE THREAD

**Issue by FuckingToasters** [Stirling-Tools/Stirling-PDF#493]
Hello, building from docker hub works fine however i want to try to build from this github repo, sadly it constantly causes following issue and i were not able to find a working solution for it on the web.

`failed to deploy a stack: failed to solve: lstat /var/lib/docker/tmp/buildkit-mount1513047715/build/libs: no such file or directory`

Here the docker-compose.yml file i use:
```yml
version: '3.0'
services:
  stirling-pdf:
    #image: frooodle/s-pdf:latest
    build: github.com/Frooodle/Stirling-PDF.git
    volumes:
      - trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - extraConfigs:/configs
      #- customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLELOGIN=true
      - SECURITY_CSRFDISABLED=false

      - SYSTEM_DEFAULTLOCALE='en-US'
      - SYSTEM_GOOGLEVISIBILITY=false
      - SYSTEM_CUSTOMSTATICFILEPATH='/customFiles/static/'

      - UI_APPNAME='PDF Toolbox'
      - UI_HOMEDESCRIPTION='We make no outbound calls for any record keeping or tracking. All files and PDFs are either purely client side, in server memory only during the execution of the task or within a temporay file only for execution of the task. Any file which has been downloaded by the user will have already been deleted from the server by that time.'
      - UI_APPNAMENAVBAR='PDF Toolbox Nav'

      - ENDPOINTS_TOREMOVE=[]
      - ENDPOINTS_GROUPSTOREMOVE=[]

      - METRICS_ENABLED=true
    networks:
      webproxy:
        ipv4_address: 172.26.0.13

networks:
  webproxy:
    external: true

volumes:
  trainingData:
  extraConfigs:
  ```
